### ISSUE TITLE
Some small minor issues what i saw

### ISSUE THREAD

**Issue by NevendyND** [Tischel/InventorySearchBar#2] opened 2022-07-30 12:23 UTC
1: The Searchbar goes into other Windows.
![image](https://user-images.githubusercontent.com/28860034/181911523-406eab4d-cc55-47c5-9229-62fb61583418.png)

2: The Mouse already changes (to windows mouse) when you enter the red line (and you can't click the fields under this)
![image](https://user-images.githubusercontent.com/28860034/181914033-7b126f04-5668-4487-831c-59ee8388ef77.png)

**Comment by NevendyND** [comment] 2022-08-22 14:52
Another "small" issue i found
When u press a Button for a Window and the Window appears behind a Plugin Window it shows this

![image](https://user-images.githubusercontent.com/28860034/185951590-bce34f84-a91e-484b-b7ad-dfa19351a1c7.png)

**Comment by NevendyND** [comment] 2022-09-03 10:56
Another Issue what i found, when the Plugin is Active and you attack with a Spell you get a micro laag when the Animations finish.
Its also not resolved when i press the Button for "Only Keybind"

**Comment by Tischel** [comment] 2022-09-04 20:19
Issue 2 is fixed in v0.5.0.0.

* I won't fix the "overlapping" issues because I think its a pretty minor problem but it's pretty hard to fix.

* The "micro lag" issue, I don't really understand how you're achieving this. I can't seem to reproduce any kind of freeze or lag. IF you can still reproduce it, please make a new issue with as much details as you can. Thanks!

**Closed by Tischel** 2022-09-04 20:19 UTC
